// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVG3I-nd1yijy7WOjpgwWwnecBYYyPrFg',
    appId: '1:38382859608:web:2bb0ed7be0e2b33452a12d',
    messagingSenderId: '38382859608',
    projectId: 'newfirebae-f910b',
    authDomain: 'newfirebae-f910b.firebaseapp.com',
    storageBucket: 'newfirebae-f910b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkDfns8amnzjoARmcoKhYNYSfz2zy5ATo',
    appId: '1:38382859608:android:3d3d105dda369bf552a12d',
    messagingSenderId: '38382859608',
    projectId: 'newfirebae-f910b',
    storageBucket: 'newfirebae-f910b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSH6tKG_2AVMCVTuxAeDmtCejHO2Y0QNo',
    appId: '1:38382859608:ios:12c5eb5203cb683f52a12d',
    messagingSenderId: '38382859608',
    projectId: 'newfirebae-f910b',
    storageBucket: 'newfirebae-f910b.appspot.com',
    iosClientId: '38382859608-laus6edkc07v3nb00283ppfa1rcvnmkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSH6tKG_2AVMCVTuxAeDmtCejHO2Y0QNo',
    appId: '1:38382859608:ios:12c5eb5203cb683f52a12d',
    messagingSenderId: '38382859608',
    projectId: 'newfirebae-f910b',
    storageBucket: 'newfirebae-f910b.appspot.com',
    iosClientId: '38382859608-laus6edkc07v3nb00283ppfa1rcvnmkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseproject',
  );
}
